# NumPy (Numerical Python)

### Biblioteca para operação com matrizes e vetores
Alternativa para as listas

In [5]:
# importação da biblioteca
import numpy as np

In [10]:
dados = [1, 3, 2, 4, 6, 1, 5, 2, 4, 5, 3, 6]
type(dados)

list

In [11]:
dados/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

### O exemplo acima resulta em um erro pois a lista não suporta operações matemáticas

In [12]:
dados_np = np.array(dados)

In [13]:
type(dados_np)

numpy.ndarray

### ndarray -> N-dimensional array
Vetor multidimensional

In [14]:
dados_np

array([1, 3, 2, 4, 6, 1, 5, 2, 4, 5, 3, 6])

In [15]:
# divisao
dados_np/2

array([0.5, 1.5, 1. , 2. , 3. , 0.5, 2.5, 1. , 2. , 2.5, 1.5, 3. ])

In [16]:
# adicao
dados_np + 2

array([3, 5, 4, 6, 8, 3, 7, 4, 6, 7, 5, 8])

In [17]:
# multplicacao
dados_np*2

array([ 2,  6,  4,  8, 12,  2, 10,  4,  8, 10,  6, 12])

In [18]:
# subtracao
dados_np - 2

array([-1,  1,  0,  2,  4, -1,  3,  0,  2,  3,  1,  4])

In [19]:
# exponenciancao
dados_np**2

array([ 1,  9,  4, 16, 36,  1, 25,  4, 16, 25,  9, 36])

## Aceita apenas um tipo de dados

In [20]:
aluno = np.array(["dalton",20, 1.86])

In [21]:
aluno

array(['dalton', '20', '1.86'], dtype='<U6')

## Comparação com listas

In [27]:
idades = [20, 19, 16, 21, 15, 13, 17, 24]

In [28]:
idades + idades

[20, 19, 16, 21, 15, 13, 17, 24, 20, 19, 16, 21, 15, 13, 17, 24]

In [29]:
np_idades = np.array(idades)
np_idades

array([20, 19, 16, 21, 15, 13, 17, 24])

In [30]:
np_idades + np_idades

array([40, 38, 32, 42, 30, 26, 34, 48])

### A `soma` na lista ocorre a concatenação, isto é, a junção entre as duas listas
### No `numpy array` ocorre a soma entre os elementos correspondentes

In [32]:
np_idades[0]

20

In [33]:
np_idades > 18

array([ True,  True, False,  True, False, False, False,  True])

In [31]:
# numpy subsetting
np_idades[np_idades > 18]

array([20, 19, 21, 24])

In [16]:
# 2d arrays (vetores 2d, matrizes)
np_2d = np.array([[10, 26, 45, 34],[1,7,4,9]])
np_2d

array([[10, 26, 45, 34],
       [ 1,  7,  4,  9]])

In [36]:
np_2d.shape

(2, 4)

### 2 linhas, 4 colunas

In [37]:
# subsetting -> acessando valores atraves do index (posicao)
np_2d[0]

array([10, 26, 45, 34])

In [41]:
# acessa a 2nda linha e a 3ra coluna
np_2d[1][3]

9

In [42]:
# acessa a 2nda linha e a 3ra coluna
np_2d[1, 3]

9

In [44]:
# acessa todas as linhas e as colunas 0 e 1 
np_2d[:, 0:2]

array([[10, 26],
       [ 1,  7]])

In [63]:
# acessa somente a 2nda linha e todas as colunas
np_2d[1, :]

array([1, 7, 4, 9])

## Estatística  com NumPy

In [6]:
from sklearn import datasets
iris_data = datasets.load_iris()

In [7]:
data = iris_data.data

In [8]:
type(data)

numpy.ndarray

In [9]:
# media da primeira coluna
np.mean(data[:, 0])

5.843333333333334

In [10]:
# mediana da primeira coluna
np.median(data[:, 0])

5.8

In [11]:
# desvio padrao da primeira coluna
np.std(data[:, 0])

0.8253012917851409

## Gerar dados em uma distribuição normal

In [12]:
# gera 100 dados aleatorios 
alturas = np.round(np.random.normal(1.75, 0.20, 100), 2)
# gera 100 dados aleatorios 
pesos = np.round(np.random.normal(65.50, 15, 100), 2)

In [14]:
# cria um vetor com duas colunas que recebe os dados criados ateriormente
pessoas = np.column_stack((alturas, pesos))

In [77]:
# gera 10 dados entre 0 e 1
corrente = np.random.rand(10)

In [78]:
corrente

array([0.01031876, 0.2048075 , 0.17647339, 0.88374303, 0.36741206,
       0.48839856, 0.46362815, 0.34867809, 0.45694984, 0.93519895])

In [81]:
# gera 10 dados entre 1 e 10
dados = np.linspace(1, 10, 10)

In [82]:
dados

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Matrizes

In [17]:
A = np.matrix([[1,2],[3,4]])

In [18]:
A

matrix([[1, 2],
        [3, 4]])

In [19]:
I = np.matrix([[1, 0],[0, 1]])

In [20]:
I

matrix([[1, 0],
        [0, 1]])

In [34]:
# criação de matrizes genéricas
zeros = np.zeros((3, 3))
ones = np.ones((3, 3))

In [29]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# produto vetorial
A.dot(I)

matrix([[1, 2],
        [3, 4]])

In [40]:
# transforma (comprime) a matriz em um vetor
A.A1

array([1, 2, 3, 4])

In [41]:
# matriz transposta
A.T

matrix([[1, 3],
        [2, 4]])

In [42]:
# matriz inversa
A.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [55]:
# retorna a diagonal principal da matriz
A.diagonal()

matrix([[1, 4]])

In [64]:
# retorna o numero de dimensoes da matriz
A.ndim

2

In [73]:
# minimo valor da matriz
A.min()

1

In [75]:
# maximo valor da matriz
A.max()

4

# Manipulação de arquivos (ler e escrever)

In [130]:
import dados

In [133]:
jogadas = dados.dados(5, 10, 6)

In [134]:
jogadas

{'jogada1': {'dado1': 3, 'dado2': 5, 'dado3': 3, 'dado4': 3, 'dado5': 3},
 'jogada2': {'dado1': 2, 'dado2': 6, 'dado3': 5, 'dado4': 6, 'dado5': 3},
 'jogada3': {'dado1': 2, 'dado2': 2, 'dado3': 6, 'dado4': 1, 'dado5': 3},
 'jogada4': {'dado1': 2, 'dado2': 4, 'dado3': 4, 'dado4': 2, 'dado5': 5},
 'jogada5': {'dado1': 1, 'dado2': 2, 'dado3': 6, 'dado4': 2, 'dado5': 1},
 'jogada6': {'dado1': 3, 'dado2': 1, 'dado3': 4, 'dado4': 2, 'dado5': 1},
 'jogada7': {'dado1': 3, 'dado2': 2, 'dado3': 5, 'dado4': 2, 'dado5': 2},
 'jogada8': {'dado1': 1, 'dado2': 2, 'dado3': 6, 'dado4': 1, 'dado5': 6},
 'jogada9': {'dado1': 5, 'dado2': 3, 'dado3': 1, 'dado4': 2, 'dado5': 3},
 'jogada10': {'dado1': 4, 'dado2': 1, 'dado3': 6, 'dado4': 2, 'dado5': 6}}